inputSet:
  name: Build_config_1688107732571-pr-trigger-input-set
  identifier: Build_config_1688107732571prtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_config_1688107732571
    properties:
      ci:
        codebase:
          build:
            type: PR
            spec:
              number: <+trigger.prNumber>
